### ISSUE TITLE
POST of scheduled vaccination returns a null date

### ISSUE THREAD

**Issue by jcairo** [icchange/Vaccinations#4]
When scheduling a vaccination the scheduled date returned is null.

##### Vaccination object posted. 
![screen shot 2015-06-12 at 12 08 56 pm](https://cloud.githubusercontent.com/assets/4959155/8136830/2f4d4202-10fc-11e5-9bf2-ae537ffb0589.png)

##### Vaccination object returned, with missing scheduled date.
![screen shot 2015-06-12 at 12 09 17 pm](https://cloud.githubusercontent.com/assets/4959155/8136829/2f4cae78-10fc-11e5-82b2-27134057edfb.png)

**Comment by Assimilator** [comment]
Should be fixed now.
