### ISSUE TITLE
Adverse reaction DELETE Does not work very very nice.

### ISSUE THREAD

**Issue by jcairo** [icchange/Vaccinations#5]
When deleting an adverse reaction 405 method not allowed displayed

```
DELETE http://208.77.196.178:64000/openmrs/ws/rest/v2/vaccinationsmodule/vaccinations/adverseReactions/6/patient/3 
```

**Comment by Assimilator** [comment]
Wrong endpoint.
Proper endpoint: /vaccinationsmodule/adversereactions/{adverseReactionId}/patient/{patientId}

**Comment by Assimilator** [comment]
changed the response type to SimpleVaccination
